language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: KIbqlyRIzOg7mpQ/vNCc3Kd7Lbz8jSct7hequC8cQ0gkklWcGUue2RpWzCwK9dScfCQZ0xrZpVV3gWXTbOUJAkNOhhboP/YGpIGm1kkQ+QlobnOrl+73Aqtzydl/YPfQYQfybAzGPX//ztcamMt/5HahSFfJZkmJP6MeSGfgjC8=
  app: ch-carpool
  on:
    repo: scsper/carpool
